# .github/workflows/build.yml
name: Build and Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, macos, windows]
    steps:
      - uses: actions/checkout@v2
      - name: Install TCC
        run: sudo apt-get install tcc
      - name: Build with TCC
        run: make CC=tcc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Add a .zip extension to the artifact name
          name: hello-${{ matrix.os }}.zip
          path: hello

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      - name: Create tag and release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hello-*"
          # Use the current date with seconds as the tag name
          tag: ${{ format('release-{0:yyyy-MM-dd-HH-mm-ss}', github.event.head_commit.timestamp) }}
          name: Release ${{ format('release-{0:yyyy-MM-dd-HH-mm-ss}', github.event.head_commit.timestamp) }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # Skip the step if the tag already exists
          if-no-files-found: skip
          # Use the .zip file as the asset_path
          asset_path: hello-${{ matrix.os }}.zip
          # Use the .zip file as the asset_name
          asset_name: hello-${{ matrix.os }}.zip
          asset_content_type: application/zip
