# .github/workflows/build.yml
name: Build and Release

on: [push]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, macos, windows]
    steps:
      - uses: actions/checkout@v2
      - name: Install TCC
        run: sudo apt-get install tcc
      - name: Build with TCC
        run: make CC=tcc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # Add a .zip extension to the artifact name
          name: hello-${{ matrix.os }}.zip
          path: hello

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
      # Add a step to get the current date in UTC using the Linux command date and save it as an output
      - name: Get current date in UTC
        id: date
        run: echo "::set-output name=date::$(date -u +%Y-%m-%d-%H-%M-%S)"
      - name: Create tag and release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "hello-*"
          # Use the output of the previous step as the tag name and release name
          tag: ${{ format('release-{0}', steps.date.outputs.date) }}
          name: Release ${{ format('release-{0}', steps.date.outputs.date) }}
          token: ${{ secrets.GITHUB_TOKEN }}
          # Skip the step if the tag already exists
          if-no-files-found: skip
          # Use the .zip file as the asset_path
          asset_path: hello-${{ matrix.os }}.zip
          # Use the .zip file as the asset_name
          asset_name: hello-${{ matrix.os }}.zip
          asset_content_type: application/zip
