# .github/workflows/build.yml
name: Build

on: [push]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, macos, windows]
    steps:
      - uses: actions/checkout@v2
      - name: Install TCC
        run: sudo apt-get install tcc
      - name: Build with TCC
        run: make CC=tcc
      - name: Zip binaries
        run: zip ${{ matrix.os }}.zip hello # Use ${{ matrix.os }} instead of ${matrix.os}
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: ${{ matrix.os }}.zip

  release:
    permissions: write-all
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts/
      - name: Create tag and release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}-${{ github.run_number }}
          release_name: Release ${{ github.ref }}-${{ github.run_number }}
          body: |
            Release generated from workflow.
          draft: false
          prerelease: false
      - name: Upload binaries as release assets
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/${{ matrix.os }}.zip # Use ${{ matrix.os }} instead of ${matrix.os}
          asset_name: ${{ matrix.os }}.zip # Use ${{ matrix.os }} instead of ${matrix.os}
          asset_content_type: application/zip

